### ISSUE TITLE
XYScriptMessage 里面的 callback 作用？

### ISSUE THREAD

**Issue by change2hao** [xiaoyouPrince/WKWebViewDemo#1]
XYScriptMessage 里面的 callback 作用能否在demo里面体现一下呢

**Comment by xiaoyouPrince** [comment]
callback 是js传过来的回调函数，比如完成 js 的功能之后，可以用webView去执行回调代码。

比如web内部可以想要请求App的图库、地理位置、分享等异步功能，App在获取完成之后可以回调相关方法，进行回传。

最近正在更新一些基础服务的统一接入功能，欢迎关注。

**Comment by xiaoyouPrince** [comment]
之前没有想过自己这个DEMO会有人关注，所以没有留意到有issue，抱歉没有回复。
