### ISSUE TITLE
你好我最近也这样的需求APP里面嵌入H5支付的

### ISSUE THREAD

**Issue by Sun7400** [xiaoyouPrince/WKWebViewDemo#2]
您好的最近有个问题想咨询下能留个联系方式吗

**Comment by xiaoyouPrince** [comment]
你可以加我微信，xiaoyouPrince




| |
xiaoyouPrince
iOS 工程师
|
|
FESCO
18211077994
邮箱：xiaoyouprince@163.com
朝阳门南大街16号
10020
|

签名由 网易邮箱大师 定制

在2020年08月10日 10:37，SunMengK 写道：

您好的最近有个问题想咨询下能留个联系方式吗
