### ISSUE TITLE
掉起支付

### ISSUE THREAD

**Issue by 979881765** [xiaoyouPrince/WKWebViewDemo#3]
麻烦问下，h5中可以直接调起微信吗

**Comment by xiaoyouPrince** [comment]
可以，README中有原理介绍




| |
xiaoyouPrince
iOS 工程师
|
|
FESCO
18211077994
***@***.***
朝阳门南大街16号
10020
|

签名由 网易邮箱大师 定制

在2021年05月06日 14:34，丶 bless 写道：

麻烦问下，h5中可以直接调起微信吗

**Comment by 979881765** [comment]
哦，我们这H5那边说掉不起微信客户端，头疼
